[project]
name = "Text2Pen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic==2.10.6",
    "gradio>=5.33.0",
]
